branches: 
  - name: release
    channel: flathub
  - name: freeze/**
    channel: gonihub
    prerelease: beta
  - name: hotfix/**
    channel: gonihub
    prerelease: "${name.split('/').slice(0, 2).join('-').toLowerCase()}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - 
    - "@semantic-release/exec"
    - prepareCmd: ./scripts/prepare-new-version.sh ${nextRelease.version} '${Buffer.from(JSON.stringify(commits)).toString('base64')}'
  - "@semantic-release/changelog"
  - 
    - "@semantic-release/git"
    - assets:
      - CMakeLists.txt
      - CHANGELOG.md
      - resources/flatpak/de.gonicus.gonnect.releases.xml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  
