import os

from conan import ConanFile
from conan.errors import ConanException
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.env import VirtualBuildEnv
from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, load, save

required_conan_version = ">=2.4"


class SnowballStemConan(ConanFile):
    name = "snowballstem"
    description = "Snowball compiler and stemming algorithms (libstemmer)"
    license = "BSD-3-Clause"
    url = "https://github.com/snowballstem/snowball"
    homepage = "https://snowballstem.org"
    topics = ("stemming", "nlp", "search", "libstemmer")

    package_type = "library"
    languages = "C"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    exports_sources = "CMakeLists.txt"

    def export_sources(self):
        export_conandata_patches(self)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")

    def layout(self):
        cmake_layout(self, src_folder="src")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        apply_conandata_patches(self)

    @property
    def _generated_folder(self):
        return os.path.join(self.build_folder, "gen")

    def _parse_modules(self):
        algorithms = {}
        aliases = {}
        encodings = set()

        modules = load(self, os.path.join(self.source_folder, "libstemmer", "modules.txt"))

        for line in modules.splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue

            algorithm, encoding_list, alias_list = line.split()[:3]
            encs = encoding_list.split(",")
            algorithms.setdefault(algorithm, set()).update(encs)
            encodings.update(encs)

            for alias in alias_list.split(","):
                aliases[alias] = algorithm

        if not algorithms:
            raise ConanException("No stemmers found in libstemmer/modules.txt")

        return ({alg: sorted(encs) for alg, encs in algorithms.items()},
                aliases,
                sorted(encodings))

    def _write_generated_sources(self):
        """Replace the perl/sed steps of the upstream GNUmakefile."""
        algorithms, aliases, encodings = self._parse_modules()

        header = ["/* Generated by the conan recipe */\n"]
        for algorithm in sorted(algorithms):
            for encoding in algorithms[algorithm]:
                header.append(f'#include "stem_{encoding}_{algorithm}.h"\n')

        header.append("\ntypedef enum {\n  ENC_UNKNOWN=0,\n")
        header.append(",\n".join(f"  ENC_{enc}" for enc in encodings))
        header.append("\n} stemmer_encoding_t;\n\n"
                      "struct stemmer_encoding {\n"
                      "  const char * name;\n"
                      "  stemmer_encoding_t enc;\n"
                      "};\n"
                      "static const struct stemmer_encoding encodings[] = {\n")

        for encoding in encodings:
            header.append(f'  {{"{encoding}", ENC_{encoding}}},\n')

        header.append("  {0,ENC_UNKNOWN}\n};\n\n"
                      "struct stemmer_modules {\n"
                      "  const char * name;\n"
                      "  stemmer_encoding_t enc;\n"
                      "  struct SN_env * (*create)(void);\n"
                      "  void (*close)(struct SN_env *);\n"
                      "  int (*stem)(struct SN_env *);\n"
                      "};\n"
                      "static const struct stemmer_modules modules[] = {\n")

        for alias in sorted(aliases):
            algorithm = aliases[alias]
            for encoding in algorithms[algorithm]:
                prefix = f"{algorithm}_{encoding}"
                header.append(f'  {{"{alias}", ENC_{encoding}, {prefix}_create_env, '
                              f"{prefix}_close_env, {prefix}_stem}},\n")

        header.append("  {0,ENC_UNKNOWN,0,0,0}\n};\n\n"
                      "static const char * algorithm_names[] = {\n")

        for algorithm in sorted(algorithms):
            header.append(f'  "{algorithm}",\n')

        header.append("  0\n};\n")
        save(self, os.path.join(self._generated_folder, "snowball_modules.h"), "".join(header))

        libstemmer_c = load(self, os.path.join(self.source_folder, "libstemmer", "libstemmer_c.in"))
        for old, new in (('#include "../include/libstemmer.h"', '#include "libstemmer.h"'),
                         ('#include "../runtime/api.h"', '#include "api.h"'),
                         ('#include "@MODULES_H@"', '#include "snowball_modules.h"')):

            if old not in libstemmer_c:
                raise ConanException(f"libstemmer_c.in does not contain '{old}' anymore")

            libstemmer_c = libstemmer_c.replace(old, new)

        save(self, os.path.join(self._generated_folder, "libstemmer.c"), libstemmer_c)

        stemmers = [f"{alg}:{enc}" for alg in sorted(algorithms) for enc in algorithms[alg]]
        save(self, os.path.join(self._generated_folder, "stemmers.cmake"),
             "set(SNOWBALL_STEMMERS {})\n".format(";".join(stemmers)))

    def generate(self):
        VirtualBuildEnv(self).generate()

        self._write_generated_sources()

        tc = CMakeToolchain(self)
        tc.cache_variables["SNOWBALL_GEN_DIR"] = self._generated_folder.replace("\\", "/")
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure(build_script_folder=os.path.join(self.source_folder, os.pardir))
        cmake.build()

    def package(self):
        copy(self, "COPYING", self.source_folder, os.path.join(self.package_folder, "licenses"))
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "both")
        self.cpp_info.set_property("cmake_file_name", "SnowballStem")
        self.cpp_info.set_property("cmake_target_name", "SnowballStem::libstemmer")

        self.cpp_info.libs = ["stemmer"]
