name: 'GOnnect prepare action [Linux build]'
description: 'Recurring tasks for CI jobs'
inputs:
  deps:
    description: 'Install Dependencies'
    default: 'true'
  qt:
    description: 'Install Qt'
    default: 'true'
  conan:
    description: 'Install conan'
    default: 'true'
outputs:
  qt-version:
    description: 'QT version'
    value: ${{ steps.get-qt.outputs.qt-version }}

runs:
  using: 'composite'
  steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2
      with:
        cmake-version: 'latest'

    - name: Install dependencies
      shell: bash
      if: inputs.deps == 'true'
      run: |
        sudo apt-get update
        sudo apt install -y ninja-build llvm llvm-dev libudev-dev libsasl2-dev libsecret-1-dev evolution-data-server-dev libnotify-dev libebook-contacts1.2-dev libebook1.2-dev libecal2.0-dev libedata-cal2.0-dev libedata-book1.2-dev git-lfs
        sudo snap install yq

    - name: Get QT-Version
      if: inputs.qt == 'true'
      id: get-qt
      uses: ./.github/actions/get-qt-version

    - name: Install Qt
      if: inputs.qt == 'true'
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ steps.get-qt.outputs.qt-version }}
        host: 'linux'
        target: 'desktop'
        modules: 'qt5compat qtmultimedia qtwebengine qtwebchannel qtnetworkauth qtpositioning qtwebsockets qtgrpc'
        arch: 'linux_gcc_64'
        cache: true

    - name: Install Conan
      if: inputs.conan == 'true'
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1
      with:
        version: 2.22.2
        cache_packages: true

    - name: Install Conan dependencies
      if: inputs.conan == 'true'
      shell: bash
      run: |
        resources/conan/export.py
        conan install . --build=missing
