name: 'GOnnect prepare action [Windows build]'
description: 'Recurring tasks for CI jobs'
outputs:
  qt-version:
    description: 'QT version'
    value: ${{ steps.get-qt.outputs.qt-version }}

runs:
  using: 'composite'
  steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2
      with:
        cmake-version: 'latest'

    - name: Install NSIS
      id: nsis
      uses: negrutiu/nsis-install@f3339c88dba6fd08910d5275a943f8f746d94876 # v2

    - name: Install `ExecDos` NSIS-plugin
      uses: negrutiu/nsis-install-plugin@c7f666810808b77249537bec2f7110e7ad9340b1 # v1
      with:
        url: https://nsis.sourceforge.io/mediawiki/images/0/0f/ExecDos.zip

    - name: Get QT-Version
      id: get-qt
      uses: ./.github/actions/get-qt-version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ steps.get-qt.outputs.qt-version }}
        host: 'windows'
        target: 'desktop'
        modules: 'qt5compat qtmultimedia qtwebengine qtwebchannel qtnetworkauth qtpositioning qtwebsockets qtgrpc qtshadertools'
        arch: 'win64_msvc2022_64'
        cache: true

    - name: Install Conan
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1
      with:
        version: 2.22.2
        cache_packages: true

    - name: Install Conan dependencies
      shell: cmd
      run: |
        conan config install resources/conan
        conan export-dependencies .
        conan install . --build=missing -s compiler.cppstd=17
