#!/usr/bin/env python3
from sh import conan
import yaml
import pathlib

recipes = pathlib.Path("recipes")
for recipe_dir in [r for r in recipes.iterdir() if r.is_dir()]:
    recipe_conf = pathlib.Path(recipe_dir, "config.yml")
    if recipe_conf.is_file():
        package_name = pathlib.PurePath(recipe_dir).name

        with open(recipe_conf) as conf:
            info = yaml.load(conf, Loader=yaml.FullLoader)
            version = list(info.get('versions').keys())[0]
            sub_path = info.get('versions').get(version).get('folder')

            print(f"Exporting {package_name} {version}...")
            conan.export(pathlib.PurePath(recipe_dir, sub_path), "--version=%s" % version)
