[template]
name=1und1

[templateField0]
name=Phonenumber
name[de]=Rufnummer
description=Your local phonenumber
description[de]=Zu registrierende Telefonnummer
regex=[0-9]+
target=PHONENUMBER
type=text

[ua]
stunTryIpv6=false
stunIgnoreFailure=true
mwiUnsolicitedEnabled=true
enableUpnp=false
upnpIfName=
maxCalls=10
natTypeInSdp=1
stunServers=stun.1und1.de

[media]
noVad=false
clockRate=16000
sndClockRate=
sndRecLatency=100
sndPlayLatency=160
quality=4
audioFramePtime=20
jbInit=-1
jbMinPre=-1
jbMaxPre=-1
jbMax=-1
ecTailLen=200

[account0]
userUri=sip:%TPL[PHONENUMBER]%@tls-sip.1und1.de
registrarUri=sip:tls-sip.1und1.de
proxies=sip:tls-sip.1und1.de
srtpUse=mandatory
srtpSecureSignaling=0
lockCodecEnabled=false
port=5061
verifyServer=false
contactRewriteUse=1
contactRewriteMethod=always-update
sipStunUse=false
mediaStunUse=true
sipUpnpUse=true
nat64Opt=false
iceEnabled=true
iceAggressiveNomination=true
iceNoRtcp=false
iceAlwaysUpdate=true
viaRewriteUse=true
sdpNatRewriteUse=false
sipOutboundUse=false
sipOutboundInstanceId=
sipOutboundRegId=
auth=auth0
transport=tls
network=ipv4

[auth0]
scheme=Plain
username=%TPL[PHONENUMBER]%
realm=*
type=plain
data=
