versions:
  "6.26.0":
    folder: "all"

updater:
  source: anitya
  id: 311432
  url-pattern: https://download.kde.org/stable/frameworks/${version_major}.${version_minor}/extra-cmake-modules-${version}.tar.xz
