name: 'GOnnect prepare action [MacOS build]'
description: 'Recurring tasks for CI jobs'
outputs:
  qt-version:
    description: 'QT version'
    value: ${{ steps.get-qt.outputs.qt-version }}


runs:
  using: 'composite'
  steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2
      with:
        cmake-version: 'latest'

    - name: Install dependencies
      shell: bash
      run: |
        brew install cyrus-sasl

    - name: Get QT-Version
      id: get-qt
      uses: ./.github/actions/get-qt-version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ steps.get-qt.outputs.qt-version }}
        host: 'mac'
        target: 'desktop'
        modules: 'qt5compat qtmultimedia qtwebengine qtwebchannel qtnetworkauth qtpositioning qtwebsockets qtgrpc'
        arch: 'clang_64'
        cache: true

    - name: Install Conan
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1
      with:
        version: 2.22.2
        cache_packages: true

    - name: Install Conan dependencies
      shell: bash
      run: |
        resources/conan/export.py
        conan install . --build=missing
