name: 'GOnnect prepare action [MacOS build]'
description: 'Recurring tasks for CI jobs'
inputs:
  qt-version:
    description: 'QT version'
    required: true
    default: '6.10.0'
  qt-only:
    description: 'Install Qt only, skip other steps'
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2
      with:
        cmake-version: 'latest'

    - name: Install dependencies
      shell: bash
      if: inputs.qt-only == 'false'
      run: |
        brew install ninja cyrus-sasl yq

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt-version }}
        host: 'mac'
        target: 'desktop'
        modules: 'qt5compat qtmultimedia qtwebengine qtwebchannel qtnetworkauth qtpositioning qtwebsockets qtgrpc'
        arch: 'clang_64'
        cache: true
