/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a KRunnerAdapter -c KRunner2Adapter -i QObject
 * specs/org.kde.krunner1.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KRUNNERADAPTER_H
#define KRUNNERADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QObject>
#include <QtCore/qcontainerfwd.h>

// HAND-EDIT - added missing include
#include "linux/LinuxDesktopSearchProvider.h"

/*
 * Adaptor class for interface org.kde.krunner1
 */
class KRunner2Adapter : public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.krunner1")
    Q_CLASSINFO("D-Bus Introspection",
                ""
                "  <interface name=\"org.kde.krunner1\">\n"
                "    <method name=\"Teardown\"/>\n"
                "    <method name=\"Config\">\n"
                "      <annotation value=\"QVariantMap\" "
                "name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "      <arg direction=\"out\" type=\"a{sv}\" name=\"config\"/>\n"
                "    </method>\n"
                "    <method name=\"Actions\">\n"
                "      <annotation value=\"ActionList\" "
                "name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "      <arg direction=\"out\" type=\"a(sss)\" name=\"matches\"/>\n"
                "    </method>\n"
                "    <method name=\"Run\">\n"
                "      <arg direction=\"in\" type=\"s\" name=\"matchId\"/>\n"
                "      <arg direction=\"in\" type=\"s\" name=\"actionId\"/>\n"
                "    </method>\n"
                "    <method name=\"Match\">\n"
                "      <arg direction=\"in\" type=\"s\" name=\"query\"/>\n"
                "      <annotation value=\"RemoteMatches\" "
                "name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "      <arg direction=\"out\" type=\"a(sssida{sv})\" name=\"matches\"/>\n"
                "    </method>\n"
                "  </interface>\n"
                "")
public:
    KRunner2Adapter(QObject *parent);
    ~KRunner2Adapter() override;

public: // PROPERTIES
public slots: // METHODS
    ActionList Actions();
    QVariantMap Config();
    RemoteMatches Match(const QString &query);
    void Run(const QString &matchId, const QString &actionId);
    void Teardown();
signals: // SIGNALS
};

#endif
