name: 'Gossip prepare action'
description: 'Recurring tasks for CI jobs'
inputs:
  qt-version:
    description: 'QT version'
    required: true
    default: '6.10.0'
  qt-only:
    description: 'Install Qt only, skip other steps'
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2
      with:
        cmake-version: 'latest'
            
    - name: Install dependencies
      shell: bash
      if: inputs.qt-only == 'false'
      run: |
        sudo apt-get update
        sudo apt install -y ninja-build llvm llvm-dev libsasl2-dev libical-dev libsecret-1-dev evolution-data-server-dev libnotify-dev libebook-contacts1.2-dev libebook1.2-dev libecal2.0-dev libedata-cal2.0-dev libedata-book1.2-dev
        sudo snap install yq
    
    - name: Install git lfs
      shell: bash
      run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt-version }}
        host: 'linux'
        target: 'desktop'
        modules: 'qt5compat qtmultimedia qtwebengine qtwebchannel qtnetworkauth qtpositioning qtwebsockets qtgrpc'
        arch: 'linux_gcc_64'
        cache: true
