#pragma once

// Common
#include <cmath>
#include <fcntl.h>
#include <grp.h>
#include <libusb.h>
#include <netdb.h>
#include <pjmedia/port.h>
#include <pjsip/sip_msg.h>
#include <pjsua2.hpp>
#include <pjsua2/media.hpp>
#include <pjsua-lib/pjsua.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <unistd.h>

// Qt
#include <QAbstractItemModel>
#include <QAbstractListModel>
#include <QApplication>
#include <QAudioDevice>
#include <QAudioFormat>
#include <QAudioInput>
#include <QAudioOutput>
#include <QAudioSink>
#include <QAudioSource>
#include <QBuffer>
#include <QCameraDevice>
#include <QClipboard>
#include <QColor>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDateTime>
#include <QDBusArgument>
#include <QDBusConnection>
#include <QDBusInterface>
#include <QDBusMessage>
#include <QDBusMetaType>
#include <QDBusObjectPath>
#include <QDBusPendingCall>
#include <QDBusPendingCallWatcher>
#include <QDBusPendingReply>
#include <QDebug>
#include <QDesktopServices>
#include <QDir>
#include <QDirIterator>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QGuiApplication>
#include <QHash>
#include <QImage>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QLibraryInfo>
#include <QList>
#include <QLocale>
#include <QLoggingCategory>
#include <QMap>
#include <QMediaDevices>
#include <QMediaFormat>
#include <QMediaPlayer>
#include <QMenu>
#include <QMetaEnum>
#include <QMimeDatabase>
#include <QMutexLocker>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QNetworkRequestFactory>
#include <QObject>
#include <QPainter>
#include <QPainterPath>
#include <QPixmap>
#include <QPluginLoader>
#include <QPointer>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQmlEngine>
#include <QQmlPropertyMap>
#include <QQuickWindow>
#include <QRandomGenerator>
#include <QRegularExpression>
#include <QSet>
#include <QSettings>
#include <QSocketNotifier>
#include <QSortFilterProxyModel>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QStack>
#include <QStandardPaths>
#include <QString>
#include <QStringList>
#include <QSystemTrayIcon>
#include <QtAudio>
#include <QtCore/QByteArray>
#include <QtCore/qcontainerfwd.h>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QMetaObject>
#include <QtCore/QObject>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QtPlugin>
#include <QtCore/QVariant>
#include <QtCrypto>
#include <QtDBus/QDBusConnection>
#include <QtDBus/QtDBus>
#include <QThread>
#include <QTimer>
#include <QtNetworkAuth/QtNetworkAuth>
#include <QtQml/qqml.h>
#include <QtQml/qqmlregistration.h>
#include <QTranslator>
#include <QtWebEngineQuick>
#include <QUrl>
#include <QUuid>
#include <QVariant>
#include <QVariantMap>
#include <qhostaddress.h>
#include <qmetaobject.h>
#include <qpa/qplatformintegration.h>
#include <qqmlintegration.h>
#include <qqmlregistration.h>
#include <qurlquery.h>
