name: GOnnect Release

on:
  workflow_dispatch:  # can be manually dispatched under GitHub's "Actions" tab
    inputs:
      dryRun:
        description: 'Dry run'
        type: 'boolean'
      skipFlatpak:
        description: 'Skip Flatpak manifest'
        type: 'boolean'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  EXT_BASE: ${{github.workspace}}

jobs:
  semantic-release:
    runs-on: ubuntu-24.04
    name: Semantic Release
    # A release will only be triggered on the release, freeze and hotfix branches.
    if: github.ref == 'refs/heads/release' || startsWith(github.ref, 'refs/heads/freeze') || startsWith(github.ref, 'refs/heads/hotfix')
    permissions:
      contents: write       # to be able to publish a GitHub release
      issues: write         # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_KEY }}
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          token: ${{ steps.get_token.outputs.token }}
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xmlstarlet jq
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          DRY_RUN_OPTION: ${{ inputs.dryRun == true && '--dry-run' || '' }}
          UPDATE_FLATPAK: ${{ inputs.skipFlatpak == true && 'NO' || 'YES' }}
        run: npx --package=semantic-release --package=@semantic-release/changelog --package=@semantic-release/git --package=@semantic-release/exec -- semantic-release $DRY_RUN_OPTION
